# Generated by Django 4.2.28 on 2026-02-27 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Daily target kcal', null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=6, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=6, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MORNING_SNACK', 'Morning Snack'), ('LUNCH', 'Lunch'), ('AFTERNOON_SNACK', 'Afternoon Snack'), ('DINNER', 'Dinner'), ('POST_WORKOUT', 'Post-Workout')], max_length=20)),
                ('food_items', models.TextField(help_text='List each food item on a new line')),
                ('notes', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet.dietplan')),
            ],
            options={
                'ordering': ['meal_type'],
            },
        ),
    ]
